name: release
on:
    push:
        tags:
            - "*.*.*"
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: corretto
            - uses: gradle/gradle-build-action@v2.4.2
            - run: chmod +x ./gradlew
            - run: ./gradlew shadowJar
            - uses: softprops/action-gh-release@v1
              with:
                  append_body: true
                  token: "${{ secrets.GITHUB_TOKEN }}"
                  files: |
                      build/libs/*.jar
